[project]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mojo-calculator"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
